services:
  couchdb:
    image: couchdb:3.3
    container_name: obsidian_db
    restart: unless-stopped
    ports:
      - "5984:5984"
    env_file:
    - ./configs/.env
    volumes:
      - ./data/couchdb:/opt/couchdb/data
      - ./configs/local.ini:/opt/couchdb/etc/local.d/local.ini
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"